# Generated by Django 2.0 on 2020-03-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_auto_20200311_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contactno', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('gender', models.CharField(default='', max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(default='', max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
