# Generated by Django 2.0 on 2020-03-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='age',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contactno',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='department',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
    ]
