# Generated by Django 2.0 on 2020-03-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_auto_20200311_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='image/')),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
