# Generated by Django 2.0 on 2020-04-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_doctors'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctors',
            table='doctors1',
        ),
    ]
