# Generated by Django 2.0 on 2020-04-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0007_auto_20200411_1345'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctors',
            table='doctors',
        ),
    ]
